### ISSUE TITLE
Solution for networking restart after supend

### ISSUE THREAD

**Issue by garibarba** [andrewwakeling/alienware-13-r3-ubuntu-16.04#3]
http://askubuntu.com/questions/761180/wifi-doesnt-work-after-suspend-after-16-04-upgrade

> Open a terminal and type the following:
> 
> `sudo nano /etc/systemd/system/wifi-resume.service`
> Now paste the script in there with a right click. Exit with CTRL + X and press Y to save. Now to activate it: sudo systemctl enable wifi-resume.service
> 
> Script:
> 
> ```
> #/etc/systemd/system/wifi-resume.service
> #sudo systemctl enable wifi-resume.service
> [Unit]
> Description=Restart networkmanager at resume
> After=suspend.target
> After=hibernate.target
> After=hybrid-sleep.target
> 
> [Service]
> Type=oneshot
> ExecStart=/bin/systemctl restart network-manager.service
> 
> [Install]
> WantedBy=suspend.target
> WantedBy=hibernate.target
> WantedBy=hybrid-sleep.target
> ```

**Comment by andrewwakeling** [comment]
Thanks for posting this solution. I'll link to this in my guide.
